// Part of currency converter project

import React,{use, useId} from 'react'


function InputBox({
    label,
    amount,
    onAmountChange, // function to handle amount change
    onCurrencyChange, // function to handle currency change
    currencyOptions = [], // array of currency options
    selectCurrency = "usd", // default selected currency
    amountDisabled = false, // flag to disable amount input
    currencyDisabled = false, // flag to disable currency select
    className = "",
}) {

    // useId is a hook that generates a unique id for the component, it is used to avoid conflicts in the DOM when multiple instances of the component are rendered.
    // It is useful when you want to generate a unique id for an element in the component
    const amountInputId = useId(); // useId hook to generate a unique id for the amount input
    console.log("selectC", selectCurrency); 
    return (
        <div className={`bg-white p-3 rounded-lg text-sm flex ${className} `}>
            <div className="w-1/2">
                <label htmlFor={amountInputId} className="text-black/70 mb-2 inline-block">
                    {label}
                </label>
                <input
                    id={amountInputId} // using the unique id generated by useId hook
                    className="outline-none w-full bg-transparent py-1.5"
                    type="number"
                    placeholder="Amount"
                    disabled={amountDisabled}
                    value={amount}
                    onChange={(e) => onAmountChange && onAmountChange(Number(e.target.value))}  // Condition for when no amount is passed or entered in the input box & if amount entered then also.
                />
            </div>
            <div className="w-1/2 flex flex-wrap justify-end text-right">
                <p className="text-black/70 mb-2 w-full">Currency Type</p>
                <select
                    className="rounded-lg px-1 py-1 bg-gray-100 cursor-pointer outline-none"
                    value={selectCurrency}
                    onChange={(e) => onCurrencyChange && onCurrencyChange(e.target.value)}
                    disabled={currencyDisabled}>

                    {currencyOptions.map((currency) => (
                        // instead index its better to use currency (unique).
                        // It is always better to use unique values like id in case of database or unique identifier for each element in the loop.
                        <option key={currency} value={currency}>
                            {/* To avoid react to create same dom multiple times. While looping in jsx we need to give a unique key to each element to have better performance in loop to repeat elements then must pass key. */}
                            {currency}
                        </option>
                    ))}


                </select>
            </div>
        </div>
    );
}

export default InputBox;


